### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by scarecrow313** [zfbx/zdiscord#4]
Hey!

First off this resource is amazing. Great work sir. Donation incoming!

I had a suggestion. It would be great if we could add role ids in the config to give out certain ace permissions. 

This helps with RP servers that use resources that are standalone and require use of ACE.

Appreciate the hard work and thanks again!

**Comment by zfbx** [comment]
I know you closed this a while ago, I wasn't fully sure at the time how to pull it off but with the rewrite I've been working on I found a nice clean way to support just that https://github.com/zfbx/zdiscord/commit/e937a990a80518ba59911f6e0fddc8b1acfbbbd1 (It does require the newest newest fivem artifacts to run since it's using node16 but it's like 100 times better )
https://github.com/zfbx/zdiscord/tree/djs
