### ISSUE TITLE
Give Role/Remove Role

### ISSUE THREAD

**Issue by GlitchOo** [zfbx/zdiscord#45]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Sometimes jobs, whitelist in particular for some cities have special discord roles that are used for out of game communication. Sometimes adding people to these roles or even removing them can be a pain especially in more active cities. It would be cool to have the ability to give a role in a hire event or something of that nature... and maybe a remove role if someone is fired.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by zfbx** [comment]
Sorry for the delay to reply, I read this after I'd just woken up and forgot. So.. somewhere I think is a snippet to add exports to do just that... yes here it is from my discord server (updated to current structure and not tested):
```js
// you'd add this to server/server/js at the bottom
global.exports("setRole", (identifier, roleId) => {
    const member = z.bot.parseMember(identifier);
    member.roles.add(roleId).catch(console.error);
});

global.exports("removeRole", (identifier, roleId) => {
    const member = z.bot.parseMember(identifier);
    member.roles.remove(roleId).catch(console.error);
});
```

then in another script where jobs are given and taken you could add
```lua
-- add
exports.zdiscord:setRole(source, "ROLEID")
-- remove
exports.zdiscord:removeRole(source, "ROLEID")
```

I wasn't sure I wanted to add this in to the main project just because of the potentials of it being abused from other scripts without the server owner's knowledge.

**Do note:** the bot's role must by higher than any role you want to give in this method in the list of roles in your discord server's settings cause it can't give/take roles above it in the hierarchy

**Comment by GlitchOo** [comment]
Oh perfect, thank you and yeah I do agree.... I could see how something like this could potentially be abused when used ignorantly. I appreciate the response.

**Comment by GlitchOo** [comment]
Just added this in and it works perfectly, thanks again.

**Comment by zfbx** [comment]
Glad to hear, I'll see about maybe making it a feature in a future version. Had a discussion with a few people about it and I think it might actually be safe to include as a resource would require needing to know so much about your server and setup for it to be abused with your server invite, role purposes and the lot so I think it might make it in :)
